services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ServerSshCommandBundle\Command\:
    resource: '../../Command/'
  ServerSshCommandBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  ServerSshCommandBundle\Repository\:
    resource: '../../Repository/'
  ServerSshCommandBundle\Service\:
    resource: '../../Service/'
